# sonar-project.properties

sonar.projectKey=insecureJava
sonar.projectName=insecureJava
sonar.projectVersion=1.0

# Source code location
sonar.sources=src/main/java
sonar.tests=src/test/java

# Java binaries (compiled classes)
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=java
